[package]
name = "msr-driver-rs"
version = "1.1.0"
edition = "2024"
license = "GPL-3.0"
description = "Minimal Rust wrapper around Windows MSR drivers (PawnIO, Scaphandre, WinRing0)"
readme = "README.md"
keywords = ["windows", "rapl", "msr", "driver", "pawnio"]
categories = ["os::windows-apis", "hardware-support"]
repository = "https://github.com/Daminoup88/msr-driver-rs"

[features]
default = ["pawnio"]
pawnio = []
scaphandre = []
winring0 = []

[dependencies]
windows-sys = { version = "0.61.2", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_IO",
  "Win32_System_Services",
  "Win32_System_Threading",
] }
